{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE MultiWayIf #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}

module Reduce.Comprehension where

import Control.Monad (foldM)
import Data.Aeson (KeyValue (..), ToJSON (..), object)
import qualified Data.DList as DList
import Data.Foldable (toList)
import qualified Data.IntMap as IntMap
import Data.List (intercalate)
import qualified Data.Map.Strict as Map
import Data.Maybe (fromJust)
import qualified Data.Sequence as Seq
import qualified Data.Text as T
import EvalAddr
import {-# SOURCE #-} Reduce.Core (reduce)
import Reduce.Monad (
  RM,
  allocRMObjID,
  comprehBindings,
  getRMContext,
  throwFatal,
 )
import Reduce.Store (lookupComprehBindingVal, withComprehBindings)
import Reduce.TraceSpan (
  debugInstStr,
  emptyTracePreDataRM,
  traceSpanTermTreeAnyTM,
  traceSpanWithRM,
 )
import Reduce.Unification (unifyVals)
import StringIndex (ShowWTIndexer (..), TextIndex, ToJSONWTIndexer (..), textIndexToBS)
import Text.Printf (printf)
import Util.Format (msprintfS, packFmtA)
import Util.Trace (withTraceScope)
import Value
import Value.Export.Debug (vnToRecursiveTermTreeString)
import Value.Instances (posttravsVT)

reduceCompreh :: EvalAddr -> Comprehension -> RM (Val, Comprehension)
reduceCompreh addr cph =
  withTraceScope (T.pack $ printf "comprehension#%d" cph.cid) $
    traceSpanWithRM "reduceCompreh" addr emptyTracePreDataRM (const (return (object []))) $ do
      r <- comprehend addr cph
      let updatedCph = cph{args = r.cphargs}
      case r.res of
        Left t -> return (t, updatedCph)
        Right revVs ->
          let vs = reverse revVs
           in if cph.isListCompreh
                then do
                  return (VList $ mkList (map mkValVN vs), updatedCph)
                else case vs of
                  [] -> return (VStruct emptyStruct, updatedCph)
                  [x] -> return (x, updatedCph)
                  _ -> do
                    res <- unifyVals (map (\x -> (addr, x)) vs) addr False
                    return (res, updatedCph)

{- | Reduce the comprehension arguments and generate the resulted struct for each iteration.

The algorithm of evaluating comprehension is as follows:

Use the nested comprehension example below to illustrate the algorithm:

for k, v in compreh_1 {
  (k): v
  sf: sfv
  {
    for k2, v2 in compreh_2_A (or sfv?) {
      (k2): v2
      (k): v2
    }
  }
  ...
}

1. at iter_1_i, bindings_1_i has been built, evaluate the tmpl struct
  1. evaluate {f1: fv1} & compreh_2_A
  2. evaluate compreh_2_A,
    1. at iter_2_A_i, bindings_2_A_i has been built, evaluate the tmpl struct of compreh_2_A
    2. the tmpl struct will be struct_2_A(bindings_2_A_i, bindings_1_i)
    2. At end, merged struct is total_struct_2_A(bindings_1_i), which is a unique struct.
  3. make the first struct, {(k): v} unique
  4. make the total_struct_2_A independent of bindings_2_A_i because the bindings will be changed.
  5. we will get a merged({fi: fvi}), total_struct_2_A), say struct_A_i. This is unique. We ensure that
     before merging, the struct_A_i is unique.
2. merge all struct_A_i generated by iter_1 into a struct.

The rules are:
1. Before merging, the struct generated by tmpl must be unique. The uniqueness of the struct is achieved by making
   fields in the template struct unique. Every time we see a template struct, we can not simply use it but need to fork
   a new struct with new field IDs.
2. For bindings lookup, we use the format of the address to determine the scope, compreh_add/clause_seg/binding_name.
   binding_name can be duplicate so the clause_seg which has the stack behavior is used to determine the scope.
3. For the mutable arguments reducing, arguments will always have the address format of compreh_add/clause_seg or
  compreh_add/clause_seg/embed_seg/clause_seg.
-}
comprehend :: EvalAddr -> Comprehension -> RM IterCtx
comprehend comprehAddr cph = comprhArg 0 emptyIterCtx{cphargs = cph.args}
 where
  comprhArg :: Int -> IterCtx -> RM IterCtx
  comprhArg i accIctx = do
    let
      arg = fromJust $ accIctx.cphargs Seq.!? i
      clauseCnstrAddr = appendTermStep comprehAddr (mkRegCnstrTermStep i)
    scope <- comprehArgScope i arg
    withTraceScope scope $
      reduceComprehArg comprehAddr comprhArg i clauseCnstrAddr arg accIctx

type ComprehContinuation = Int -> IterCtx -> RM IterCtx

reduceComprehArg :: EvalAddr -> ComprehContinuation -> Int -> EvalAddr -> ComprehArg -> IterCtx -> RM IterCtx
reduceComprehArg comprehAddr continue i clauseAddr arg ictx = case arg of
  ComprehArgTmpl vnode -> reduceTemplateArg clauseAddr vnode ictx
  ComprehArgLet name vnode -> reduceLetArg comprehAddr continue i clauseAddr name vnode ictx
  ComprehArgIf vnode -> reduceIfArg comprehAddr continue i clauseAddr vnode ictx
  ComprehArgFor key valueM vnode -> reduceForArg comprehAddr continue i clauseAddr key valueM vnode ictx

reduceTemplateArg :: EvalAddr -> VNode -> IterCtx -> RM IterCtx
reduceTemplateArg clauseAddr vnode ictx =
  traceSpanTermTreeAnyTM "comprhArg template" clauseAddr vnode $ do
    forked <- forkTemplate vnode
    resolved <- replaceIterValRefs clauseAddr forked
    reduced <- reduce clauseAddr resolved
    debugTemplate clauseAddr reduced
    return $
      ictx
        { res = (value reduced :) <$> ictx.res
        , iterCnt = ictx.iterCnt + 1
        }

reduceLetArg :: EvalAddr -> ComprehContinuation -> Int -> EvalAddr -> TextIndex -> VNode -> IterCtx -> RM IterCtx
reduceLetArg comprehAddr continue i clauseAddr name vnode ictx =
  traceSpanTermTreeAnyTM (clauseTraceMsg "let" i) clauseAddr vnode $ do
    reduced <- reduce clauseAddr vnode
    let updated = updateArg i (ComprehArgLet name reduced) ictx
    case reduced of
      IsUnknown -> earlyStop comprehAddr i updated
      IsBottom _ -> return updated{res = Left $ value reduced}
      _ -> withComprehBindings [(name, reduced)] $ continue (i + 1) updated

reduceIfArg :: EvalAddr -> ComprehContinuation -> Int -> EvalAddr -> VNode -> IterCtx -> RM IterCtx
reduceIfArg comprehAddr continue i clauseAddr vnode ictx =
  traceSpanTermTreeAnyTM (clauseTraceMsg "if" i) clauseAddr vnode $ do
    reduced <- reduce clauseAddr vnode
    let updated = updateArg i (ComprehArgIf reduced) ictx
    case reduced of
      IsUnknown -> earlyStop comprehAddr i updated
      IsBottom _ -> return updated{res = Left $ value reduced}
      _ -> continueIf continue i updated reduced

continueIf :: ComprehContinuation -> Int -> IterCtx -> VNode -> RM IterCtx
continueIf continue i ictx vnode = case rtrAtom (value vnode) of
  Just (Bool True) -> continue (i + 1) ictx
  -- Do not go to the next clause if the condition is false.
  Just (Bool False) -> return ictx
  _ ->
    continue
      (i + 1)
      ictx{res = Left $ mkBottomVal $ printf "if condition must be boolean; received %s" (showValType $ value vnode)}

reduceForArg ::
  EvalAddr -> ComprehContinuation -> Int -> EvalAddr -> TextIndex -> Maybe TextIndex -> VNode -> IterCtx -> RM IterCtx
reduceForArg comprehAddr continue i clauseAddr key valueM vnode ictx =
  traceSpanTermTreeAnyTM (clauseTraceMsg "for" i) clauseAddr vnode $ do
    reduced <- reduce clauseAddr vnode
    let updated = updateArg i (ComprehArgFor key valueM reduced) ictx
    if
      | Just _ <- rtrIncomplete (value reduced) -> earlyStop comprehAddr i updated
      | IsBottom _ <- reduced -> return updated{res = Left $ value reduced}
      -- TODO: only iterate optional fields
      | Just struct <- rtrStruct (value reduced) -> iterateStruct continue i clauseAddr key valueM struct updated
      | Just (List{store}) <- rtrList (value reduced) -> iterateList continue i clauseAddr key valueM (toList store) updated
      | otherwise ->
          return
            updated
              { res = Left $ mkBottomVal $ printf "for source is not iterable: %s" (showValType $ value reduced)
              }

iterateStruct ::
  ComprehContinuation -> Int -> EvalAddr -> TextIndex -> Maybe TextIndex -> Struct -> IterCtx -> RM IterCtx
iterateStruct continue i clauseAddr key valueM struct ictx =
  foldIterations
    ( \acc (labelIdx, field) -> do
        label <- textIndexToBS labelIdx
        let bindings = case valueM of
              Nothing -> [(key, ssfValue field)]
              Just valueName -> [(key, mkAtomVN (String label)), (valueName, ssfValue field)]
        labelT <- tshow labelIdx
        withTraceScope ("iter[" <> labelT <> "]") $
          traceSpanTermTreeAnyTM "comoprhArg for iter" clauseAddr (value $ ssfValue field) $
            continueWithBindings continue i bindings acc
    )
    ictx
    (Map.toList struct.stcFields)

iterateList ::
  ComprehContinuation -> Int -> EvalAddr -> TextIndex -> Maybe TextIndex -> [VNode] -> IterCtx -> RM IterCtx
iterateList continue i clauseAddr key valueM elements ictx =
  foldIterations
    ( \acc (idx, element) -> do
        let bindings = case valueM of
              Nothing -> [(key, mkAtomVN (Int idx))]
              Just valueName -> [(key, mkAtomVN (Int idx)), (valueName, element)]
        withTraceScope (T.pack $ printf "iter[%d]" idx) $
          traceSpanTermTreeAnyTM "comoprhArg for iter" clauseAddr element $
            continueWithBindings continue i bindings acc
    )
    ictx
    (zip [0 ..] elements)

continueWithBindings :: ComprehContinuation -> Int -> [(TextIndex, VNode)] -> IterCtx -> RM IterCtx
continueWithBindings continue i bindings =
  withComprehBindings bindings . continue (i + 1)

foldIterations :: (IterCtx -> a -> RM IterCtx) -> IterCtx -> [a] -> RM IterCtx
foldIterations step = foldM $ \ictx item ->
  if ictx.incomplete then return ictx else step ictx item

updateArg :: Int -> ComprehArg -> IterCtx -> IterCtx
updateArg i arg ictx =
  ictx{cphargs = Seq.update i arg ictx.cphargs}

clauseTraceMsg :: String -> Int -> String
clauseTraceMsg title i = printf "comoprhArg %s_clause_%d" title i

debugTemplate :: EvalAddr -> VNode -> RM ()
debugTemplate clauseAddr vnode =
  debugInstStr
    "comprehend"
    clauseAddr
    ( do
        rep <- vnToRecursiveTermTreeString vnode
        msprintfS "comprehension tmpl arg: %s" [packFmtA rep]
    )

earlyStop :: EvalAddr -> Int -> IterCtx -> RM IterCtx
earlyStop comprehAddr i ictx = do
  debugInstStr
    "comprehend"
    comprehAddr
    (return $ printf "early stop at iteration %d because step %d has no value" ictx.iterCnt i)
  return ictx{incomplete = True}

comprehArgScope :: Int -> ComprehArg -> RM T.Text
comprehArgScope i arg = case arg of
  ComprehArgFor key valueM _ -> do
    keyT <- tshow key
    valueT <- mapM tshow valueM
    return $ case valueT of
      Nothing -> T.pack $ printf "for_%d(%s)" i (T.unpack keyT)
      Just value -> T.pack $ printf "for_%d(%s,%s)" i (T.unpack keyT) (T.unpack value)
  ComprehArgIf _ -> return $ T.pack $ printf "if_%d" i
  ComprehArgLet name _ -> do
    nameT <- tshow name
    return $ T.pack $ printf "let_%d(%s)" i (T.unpack nameT)
  ComprehArgTmpl _ -> return $ T.pack $ printf "template_%d" i

-- | Fork the struct template for the comprehension iteration.
forkTemplate :: VNode -> RM VNode
forkTemplate v@VNode{constraints} = case v of
  -- Whether the struct is a sole constraint or a base constraint, it is the first constraint in the constraints
  -- sequence.
  StaticConstraints (ValCnstr vc@(ValConstraint{vcVal = VStruct struct}) Seq.:<| rest) -> do
    newStruct <- mkUniqueStruct struct
    return $ mapConstraints (\c -> c{static = ValCnstr (vc{vcVal = VStruct newStruct}) Seq.:<| rest}) v
  StaticConstraints
    (StructEmbedCnstr (ValCnstr vc@(ValConstraint{vcVal = VStruct struct}) Seq.:<| rest) Seq.:<| Seq.Empty) -> do
      newStruct <- mkUniqueStruct struct
      return $
        mapConstraints
          (\c -> c{static = Seq.singleton $ StructEmbedCnstr (ValCnstr (vc{vcVal = VStruct newStruct}) Seq.:<| rest)})
          v
  _ -> throwFatal $ "forkTemplate requires a struct template; received " ++ show constraints

{- | Resolve the references that point to the iteration variable and replace them with the reduced value.

Selectors might not be ready.
-}
replaceIterValRefs :: EvalAddr -> VNode -> RM VNode
replaceIterValRefs tmplAddr tmplV = do
  bindings <- comprehBindings <$> getRMContext
  debugInstStr
    "replaceIterValRefs"
    tmplAddr
    ( do
        let xs = toList bindings
        xsT <-
          mapM
            ( mapM
                ( \(k, v) -> do
                    kT <- tshow k
                    vT <- tshow v
                    let
                      s :: String
                      s = printf "%s: %s" (T.unpack kT) (T.unpack vT)
                    return s
                )
            )
            xs
        return $ show xsT
    )
  debugInstStr
    "replaceIterValRefs"
    tmplAddr
    ( do
        rep <- vnToRecursiveTermTreeString tmplV
        msprintfS "tmpl before replacing refs: %s" [packFmtA rep]
    )

  let vt' =
        posttravsVT
          ( \_ x ->
              case x of
                IsRef _ ref
                  | ref.resolvedIdentType == ITIterBinding
                  , Just cIdx <- ref.resolvedComprehClauseIdx
                  , Just vn <- lookupComprehBindingVal cIdx ref.ident bindings ->
                      if null ref.selectors
                        then VTVal (value vn)
                        else
                          let newIndx =
                                -- FIXME: better logic
                                ValueSelect
                                  { bvID = 0 -- It should not be referenced, as bindings have been reduced.
                                  , iSelectors = ref.selectors
                                  , -- FIXME
                                    iSelectorTypes = undefined
                                  , base = vn
                                  }
                           in VTOp (VSelect newIndx)
                _ -> x
          )
          tmplAddr
          (VTVNode tmplV)
  return $ vtVNodeOr id tmplV vt'

mkUniqueStruct :: Struct -> RM Struct
mkUniqueStruct struct = do
  sid <- allocRMObjID
  newDynPairs <-
    mapM
      ( \df -> do
          oid <- allocRMObjID
          return (oid, df{dsfID = oid}, df.dsfID)
      )
      (IntMap.elems struct.stcDynFields)
  let newDyns = IntMap.fromList $ map (\(newID, df, _) -> (newID, df)) newDynPairs

  newCnstrPairs <-
    mapM
      ( \cnstr -> do
          cid <- allocRMObjID
          return (cid, cnstr{scsID = cid})
      )
      (IntMap.elems struct.stcCnstrs)
  let newCnstrs = IntMap.fromList newCnstrPairs
      dynIDMap = IntMap.fromList $ map (\(newID, _, oldID) -> (oldID, newID)) newDynPairs
      newOrdLabels =
        DList.map
          ( \case
              StructStaticFieldLabel name -> StructStaticFieldLabel name
              StructDynFieldOID oldID -> StructDynFieldOID (fromJust $ IntMap.lookup oldID dynIDMap)
          )
          struct.stcOrdLabels
  return
    struct
      { stcID = sid
      , stcDynFields = newDyns
      , stcCnstrs = newCnstrs
      , stcOrdLabels = newOrdLabels
      }

data IterCtx = IterCtx
  { iterCnt :: Int
  -- ^ The count of the iterations.
  , incomplete :: Bool
  , cphargs :: Seq.Seq ComprehArg
  , res :: Either Val [Val]
  -- ^ It contains a list of reversed resulted structs that are generated by each iteration.
  }
  deriving (Show)

instance ToJSON IterCtx where
  toJSON IterCtx{iterCnt} = object ["iterCnt" .= iterCnt]

instance ToJSONWTIndexer IterCtx where
  ttoJSON i = do
    r <- case i.res of
      Left t -> do
        tRep <- oneLinerStringOfVNode (mkValVN t)
        return $ toJSON tRep
      Right ts -> do
        tReps <- mapM (oneLinerStringOfVNode . mkValVN) ts
        return $ toJSON tReps
    return $
      object
        [ "iterCnt" .= i.iterCnt
        , "res" .= r
        ]

emptyIterCtx :: IterCtx
emptyIterCtx = IterCtx{iterCnt = 0, res = Right [], incomplete = False, cphargs = Seq.empty}

tshowBindings :: Map.Map EvalAddr Val -> RM T.Text
tshowBindings binds = do
  pairs <-
    mapM
      ( \(nameIdx, v) -> do
          name <- tshow nameIdx
          vT <- tshow v
          return $ printf "%s: %s" (T.unpack name) (T.unpack vT)
      )
      (Map.toList binds)
  return $ T.pack $ "{" ++ intercalate ", " pairs ++ "}"
