{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE MultiWayIf #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}

module Reduce.Disjunction where

import Control.Monad (foldM, when)
import Data.Foldable (toList)
import Data.Maybe (isJust)
import qualified Data.Sequence as Seq
import qualified Data.Set as Set
import Feature
import {-# SOURCE #-} Reduce.Core (reduceVal)
import Reduce.Monad (
  RM,
  throwFatal,
 )
import Reduce.TraceSpan (
  debugInstStr,
  mkTracePreDataWithOnlyVal,
  traceSpanNoPreRM,
  traceSpanRM,
  traceSpanWithRM,
 )
import StringIndex (ShowWTIndexer (..))
import Text.Printf (printf)
import Util.Format (msprintfS, packFmtA)
import Value
import Value.Export.Debug (termsRepToJSONWithAddr, valToStringTermsRep, vnToStringTermsRep)

reduceDisj :: ValAddr -> Disj -> RM Val
reduceDisj addr d = traceSpanNoPreRM "reduceDisj" addr $ do
  -- We have to reduce all disjuncts because some of the disjuncts might be created by unifying, which could still have
  -- unknown value.
  d' <- vtmapM (applyAddrFOnVal reduceVal) addr d
  normalizeDisj addr d'

resolveDisjOp :: DisjoinOp -> ValAddr -> RM Val
resolveDisjOp disjOp addr = traceSpanNoPreRM "resolveDisjOp" addr $ do
  let terms = toList $ djoTerms disjOp
  when (length terms < 2) $
    throwFatal $
      printf "disjunction operation requires at least 2 terms, got %d" (length terms)

  disjuncts <- procMarkedTerms terms
  debugInstStr
    "resolveDisjOp"
    addr
    ( do
        disjunctTs <- mapM valToStringTermsRep disjuncts
        msprintfS "disjuncts: %s" [packFmtA disjunctTs]
    )
  if null disjuncts
    -- If none of the disjuncts are ready, return Nothing.
    then return VUnknown
    else do
      let d = emptyDisj{dsjDisjuncts = Seq.fromList disjuncts}
      normalizeDisj addr d

{- | Normalize a disjunction which is generated by reducing a disjunction operation.

1. Flatten the disjunction.
2. Deduplicate the disjuncts.
3. Remove the bottom disjuncts.
4. If the disjunct is left with only one element, return the value.
5. If the disjunct is left with no elements, return the first bottom it found.
-}
normalizeDisj :: ValAddr -> Disj -> RM Val
normalizeDisj addr d = traceSpanRM
  "normalizeDisj"
  addr
  (mkTracePreDataWithOnlyVal <$> termsRepToJSONWithAddr addr (mkDisjVN d))
  $ do
    flattened <- flattenDisjunction d
    final <- rewriteDisjuncts flattened addr
    debugInstStr
      "normalizeDisj"
      addr
      ( do
          flattenedRep <- vnToStringTermsRep (mkDisjVN flattened)
          rep <- vnToStringTermsRep (mkDisjVN final)
          return $ printf "flattened: %s, final: %s" flattenedRep rep
      )
    if
      | null final.dsjDisjuncts ->
          let
            unknowns = filter (\case VUnknown -> True; _ -> False) (toList flattened.dsjDisjuncts)
            bottoms = filter (isJust . rtrBottom) (toList flattened.dsjDisjuncts)
           in
            if
              | length unknowns == length flattened.dsjDisjuncts -> return VUnknown
              | not (null bottoms) -> return $ head bottoms
              | otherwise ->
                  throwFatal $ printf "normalizeDisj: no disjuncts left in %s" (show flattened.dsjDisjuncts)
      -- When there is only one disjunct and the disjunct is not default, the disjunction is converted to the disjunct.
      | length final.dsjDisjuncts == 1 && null (dsjDefIndexes final) -> return $ head (toList final.dsjDisjuncts)
      | otherwise -> return $ VDisj final

{- | Flatten the disjunction.

Because disjunction operation is associative, we can flatten the disjuncts. The nested disjunctions were like
parenthesized disjunctions. For example, (a | *b) | c | (d | e) = a | *b | c | d | e.

Notice before this step, there is no marked terms in the disjunction. For example, *(a | *b) has been reduced to (a |
*b).

This handles the case where a marked term is a reference. For example the f of the *f | v1 would be <f, f> if we use the
value-default pair. When the value of the f changes to a disjunction like *1 | 2, the flattened disjuncts would be 1 and
2 with the default index of di, where di is the index of the disjunct f. When the value of f changes to 1 | 2, the
flattened disjuncts would be 1 and 2 with the default indexes of di and di + 1.

It also follows the rules of disjunction operation:
D0: ⟨v1⟩ | ⟨v2⟩         => ⟨v1|v2⟩
D1: ⟨v1, d1⟩ | ⟨v2⟩     => ⟨v1|v2, d1⟩
D2: ⟨v1, d1⟩ | ⟨v2, d2⟩ => ⟨v1|v2, d1|d2⟩

TODO: more efficiency
-}
flattenDisjunction :: Disj -> RM Disj
flattenDisjunction (Disj{dsjDefIndexes = idxes, dsjDisjuncts = disjuncts}) = do
  debugInstStr
    "flattenDisjunction"
    emptyValAddr
    ( do
        reps <- mapM valToStringTermsRep (toList disjuncts)
        return $ printf "before disjuncts: %s, defIdxes: %s" (show reps) (show idxes)
    )

  -- Use foldl because the new default indexes are based on the length of the accumulated disjuncts.
  (newIndexes, newDisjs) <- foldM flatten ([], []) (zip [0 ..] (toList disjuncts))
  return $ emptyDisj{dsjDefIndexes = newIndexes, dsjDisjuncts = Seq.fromList newDisjs}
 where
  origDefIdxesSet = Set.fromList idxes
  -- Suppose we are processing the ith disjunct, and we have accumulated the disjuncts xs.
  -- If the ith disjunct is not a disjunction, then we can just add it to the disjuncts. We also need to add the index
  -- to the default indexes if it belongs to the default disjunction.
  flatten :: ([Int], [Val]) -> (Int, Val) -> RM ([Int], [Val])
  flatten (accIs, accDs) (origIdx, t) = do
    debugInstStr
      "flattenDisjunction"
      emptyValAddr
      ( do
          vT <- tshow t
          return $ printf "At %s, val: %s" (show origIdx) (show vT)
      )
    case rtrDisj t of
      Just sub -> do
        Disj{dsjDefIndexes = subDefIndexes, dsjDisjuncts = subDisjs} <- flattenDisjunction sub
        let
          -- Add offset to the indexes of the new disjuncts. The offset is the length of the accumulated disjuncts.
          newDefIndexes =
            -- If no sub defaults found for the disjunct but the disjunct is a default disjunct, that means the
            -- disjunct has been flattened to multiple disjuncts.
            if null subDefIndexes && origIdx `Set.member` origDefIdxesSet
              then map (+ length accDs) [0 .. length subDisjs - 1]
              else map (+ length accDs) subDefIndexes
        return (accIs ++ newDefIndexes, accDs ++ toList subDisjs)
      _ ->
        return
          ( if origIdx `Set.member` origDefIdxesSet
              -- The index of the new disjunct is the length of the accumulated disjuncts.
              then accIs ++ [length accDs]
              else accIs
          , accDs ++ [t]
          )

{- | Remove unwanted or rewrite the disjuncts.

All the disjuncts have been reduced before this step.

Unwanted disjuncts include:

* duplicate default disjuncts
* duplicate disjuncts
* bottom disjuncts

Rewrite includes:

* IsRefCycle
* Struct with embedded value

TODO: consider make t an instance of Ord and use Set to remove duplicates.
-}
rewriteDisjuncts :: Disj -> ValAddr -> RM Disj
rewriteDisjuncts idisj@(Disj{dsjDefIndexes = dfIdxes, dsjDisjuncts = disjuncts}) addr =
  traceSpanWithRM
    "rewriteDisjuncts"
    addr
    (mkTracePreDataWithOnlyVal <$> termsRepToJSONWithAddr addr (mkDisjVN idisj))
    (termsRepToJSONWithAddr addr . mkDisjVN)
    $ do
      (newIndexes, newDisjs) <- foldM go ([], []) (zip [0 ..] (toList disjuncts))
      return $ emptyDisj{dsjDefIndexes = newIndexes, dsjDisjuncts = Seq.fromList newDisjs}
 where
  defValues = map (disjuncts `Seq.index`) dfIdxes
  origDefIdxesSet = Set.fromList dfIdxes

  discardDisjunct = isJust . rtrBottom

  go :: ([Int], [Val]) -> (Int, Val) -> RM ([Int], [Val])
  go (accIs, accDisjs) (idx, v) = do
    case v of
      -- FIXME: is the following case possible?
      VStruct Struct{stcEmbedVal = Just ev} -> updateDisjuncts (accIs, accDisjs) (idx, ev)
      _ -> updateDisjuncts (accIs, accDisjs) (idx, v)

  updateDisjuncts :: ([Int], [Val]) -> (Int, Val) -> RM ([Int], [Val])
  updateDisjuncts (accIs, accXs) (idx, x) = do
    let
      -- A disjunct is new if it is not in the accumulated disjuncts and it is not a Unknown disjunct.
      -- A Unknown disjunct indicates it is still unknown.
      isNewDisj = not (x `elem` accXs) && x /= VUnknown
      -- If the disjunct is equal to the default value. Note that it does not mean the disjunct is the original default
      -- value.
      isValEqDef = x `elem` defValues && x /= VUnknown
      -- The disjunct is kept if all of the following conditions are met:
      -- 1. it is not a bottom disjunct.
      -- 2. it is a new disjunct
      -- 3. it is not a default value OR it is one of the default disjuncts and its index is in the original default
      -- indexes.
      -- The second condition makes sure the relative order of the default disjuncts is kept.
      -- For example, *b | c | a | b | *a should be reduced to <b | c | a, 0|2>.
      isDiscarded = discardDisjunct x
      keepDisjunct =
        not isDiscarded
          && isNewDisj
          && (not isValEqDef || idx `Set.member` origDefIdxesSet)
      -- The disjunct is default if it is one of the default disjuncts and it is not seen before.
      isDefIndex = keepDisjunct && isValEqDef
    debugInstStr
      "rewriteDisjuncts"
      addr
      ( do
          xT <- tshow x
          xRep <- valToStringTermsRep x
          return $
            printf
              "At %s, disjunct: %s, isDiscarded: %s isValEqDef: %s, keepDisjunct: %s, isDefIndex: %s, v: %s"
              (show idx)
              xT
              (show isDiscarded)
              (show isValEqDef)
              (show keepDisjunct)
              (show isDefIndex)
              xRep
      )
    return -- Add the current disjunct index to the default indexes if condition is met.
      ( if isDefIndex then accIs ++ [length accXs] else accIs
      , if keepDisjunct then accXs ++ [x] else accXs
      )

{- | Construct a list of disjuncts from the disjunction terms.

Some existing rules for marked disjunctions:
M0:  ⟨v⟩    => ⟨v⟩        don't introduce defaults for unmarked term
M1: *⟨v⟩    => ⟨v, v⟩     introduce identical default for marked term
M2: *⟨v, d⟩ => ⟨v, d⟩     keep existing defaults for marked term
M3:  ⟨v, d⟩ => ⟨v⟩        strip existing defaults from unmarked term
-}
procMarkedTerms :: [DisjTerm] -> RM [Val]
procMarkedTerms terms = do
  -- disjoin operation allows incompleteness.
  let hasMarked = any dstMarked terms
  debugInstStr
    "procMarkedTerms"
    emptyValAddr
    ( do
        termReps <- mapM tshow terms
        return $ printf "terms: %s, hasMarked: %s" (show termReps) (show hasMarked)
    )
  return $
    foldr
      ( \term accDisjuncts ->
          let v = value $ dstValue term
           in if
                -- Apply Rule M1 and M2
                | hasMarked && dstMarked term ->
                    VDisj
                      ( maybe
                          -- Rule M1
                          (emptyDisj{dsjDefIndexes = [0], dsjDisjuncts = Seq.singleton v})
                          ( \d ->
                              if null (dsjDefIndexes d)
                                -- Rule M1
                                then d{dsjDefIndexes = [0 .. length (dsjDisjuncts d)]}
                                -- Rule M2
                                else d
                          )
                          (rtrDisj v)
                      )
                      : accDisjuncts
                -- Apply Rule M0 and M3
                | hasMarked ->
                    maybe
                      v
                      (\d -> VDisj $ d{dsjDefIndexes = []})
                      (rtrDisj v)
                      : accDisjuncts
                | otherwise -> v : accDisjuncts
      )
      []
      terms
